In [ ]:
#Description of dataset

#This dataset reflects the daily volume of violations that have occurred in 
#Children's Safety Zones for each camera. The data reflects violations that occurred from 
#July 1, 2014 until present, minus the most recent 14 days. This data may change 
#due to occasional time lags between the capturing of a potential violation and the 
#processing and determination of a violation. The most recent 14 days are not shown due to 
#revised data being submitted to the City of Chicago. The reported violations are those that 
#have been collected by the camera and radar system and reviewed by two separate City contractors. 
#In some instances, due to the inability the registered owner of the offending vehicle, 
#the violation may not be issued as a citation. However, this dataset contains all violations 
#regardless of whether a citation was issued, which provides an accurate view into the Automated 
#Speed Enforcement

In [ ]:
#The problem
# The dataset contains information about the number of violations that have occured in children safty zones
# these violations could create dangerous situations for childeren. By understanding how many violations are occuring 
# this could help the city with planing more police presence in these safty zones with high violations. 

# Question: Where are violations occuring the most? What date/timeframe are violations occuring. 
# The question will help us see if the violations are occuing during the school year. The information
# could be used to help the city of chicago understand which areas need more policing watching during the school
# year to improve saftey of kids.

In [ ]:
#The potential solution/hypothesis

#High number of violations will occur during the school year

In [ ]:
#The method of testing the solution
#Describe the design of the experiment, the analysis plan, and set benchmarks:

#Install cameras on all children safty zone, monitor and record the violations for several years. 
# The variables of interest is the location and data/time
# we will compare the variables by looking at the data year over year. Year 1 (first recording of data) will be used
# as the control sample. Last year will be used as the sample test. If the violations have increased with our two variables
# by 10% then we can conclude violations have increased for the variable location and date/time
# this expirement will use the A/B testing method.

In [ ]:
#Experiment Rollout plan
#copy of the dataset containing the first year and last year.

#Rollout plan
#The expirement will place cameras on all of the children safty zone and record all violations that have occured. 
#The experirment will run for several years. The cameras will be installed gradually over time but we will have a 
#a lot of data to use as our population. 

#success metrics
# we will see an increased number of violations during the school year. 

#secondary metrics
#increased number of violations during the school year will occur around the downtown location.

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from scipy import stats
import plotly.plotly as py
import plotly.graph_objs as go

In [2]:
df = pd.read_csv('speed-camera-violations.csv')

In [3]:
#Lets describe the data to see what the statistical data set contains
df.describe()

          VIOLATIONS  X COORDINATE  Y COORDINATE       LATITUDE      LONGITUDE
count  156781.000000  1.507160e+05  1.507160e+05  150716.000000  150716.000000
mean       29.343345  1.159799e+06  1.893458e+06      41.863348     -87.688908
std        37.153440  1.562411e+04  3.211875e+04       0.088322       0.056837
min         1.000000  1.131748e+06  1.820629e+06      41.663174     -87.790832
25%         7.000000  1.149841e+06  1.868078e+06      41.793493     -87.725084
50%        16.000000  1.159529e+06  1.898488e+06      41.877243     -87.688862
75%        37.000000  1.167170e+06  1.920968e+06      41.938988     -87.662810
max       479.000000  1.203645e+06  1.943342e+06      42.000260     -87.529848

In [4]:
df.head(10)

,ADDRESS,CAMERA ID,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,7738 S WESTERN,CHI065,2014-07-08T00:00:00,65,NaN,NaN,NaN,NaN,NaN
1,1111 N HUMBOLDT,CHI010,2014-07-16T00:00:00,56,NaN,NaN,NaN,NaN,NaN
2,5520 S WESTERN,CHI069,2014-07-08T00:00:00,10,NaN,NaN,NaN,NaN,NaN
3,1111 N HUMBOLDT,CHI010,2014-07-26T00:00:00,101,NaN,NaN,NaN,NaN,NaN
4,5529 S WESTERN,CHI068,2014-08-03T00:00:00,20,NaN,NaN,NaN,NaN,NaN
5,1111 N HUMBOLDT,CHI010,2014-07-30T00:00:00,66,NaN,NaN,NaN,NaN,NaN
6,5520 S WESTERN,CHI069,2014-07-28T00:00:00,18,NaN,NaN,NaN,NaN,NaN
7,5520 S WESTERN,CHI069,2014-07-16T00:00:00,17,NaN,NaN,NaN,NaN,NaN
8,5520 S WESTERN,CHI069,2014-07-24T00:00:00,11,NaN,NaN,NaN,NaN,NaN
9,5520 S WESTERN,CHI069,2014-07-25T00:00:00,14,NaN,NaN,NaN,NaN,NaN

In [5]:
#looking at the data, I want to make the Violation data a true continuous variable
#therefore, I will use the next few cells to remove the time componet from the cell block
df['VIOLATION DATE'][0]

'2014-07-08T00:00:00'

In [6]:
#split the cell for each -
df['VIOLATION DATE'][0].split('-')

['2014', '07', '08T00:00:00']

In [7]:
#test that I split the cell correctly
df['VIOLATION DATE'][0].split('-')[0:2]

['2014', '07']

In [8]:
#Now rejoin the split cell to contain just the month and year
'-'.join(df['VIOLATION DATE'][0].split('-')[0:2])

'2014-07'

In [9]:
#create a function to perform the split operation on all of the records for the Violation date column
def new_string(String1):
    return '-'.join(String1.split('-')[0:2])

In [10]:
#Add a column to the table to reflect the changes of the split
df['VIOLATION_MONTH'] = df['VIOLATION DATE'].apply(lambda x: new_string(x))

In [11]:
#verify the new column was added 
df

,ADDRESS,CAMERA ID,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION,VIOLATION_MONTH
0,7738 S WESTERN,CHI065,2014-07-08T00:00:00,65,NaN,NaN,NaN,NaN,NaN,2014-07
1,1111 N HUMBOLDT,CHI010,2014-07-16T00:00:00,56,NaN,NaN,NaN,NaN,NaN,2014-07
2,5520 S WESTERN,CHI069,2014-07-08T00:00:00,10,NaN,NaN,NaN,NaN,NaN,2014-07
3,1111 N HUMBOLDT,CHI010,2014-07-26T00:00:00,101,NaN,NaN,NaN,NaN,NaN,2014-07
4,5529 S WESTERN,CHI068,2014-08-03T00:00:00,20,NaN,NaN,NaN,NaN,NaN,2014-08
5,1111 N HUMBOLDT,CHI010,2014-07-30T00:00:00,66,NaN,NaN,NaN,NaN,NaN,2014-07
6,5520 S WESTERN,CHI069,2014-07-28T00:00:00,18,NaN,NaN,NaN,NaN,NaN,2014-07
7,5520 S WESTERN,CHI069,2014-07-16T00:00:00,17,NaN,NaN,NaN,NaN,NaN,2014-07
8,5520 S WESTERN,CHI069,2014-07-24T00:00:00,11,NaN,NaN,NaN,NaN,NaN,2014-07
9,5520 S WESTERN,CHI069,2014-07-25T00:00:00,14,NaN,NaN,NaN,NaN,NaN,2014-07
10,5529 S WESTERN,CHI068,2014-07-17T00:00:00,3,NaN,NaN,NaN,NaN,NaN,2014-07
11,5529 S WESTERN,CHI068,2014-07-11T00:00:00,12,NaN,NaN,NaN,NaN,NaN,2014-07
12,5520 S WESTERN,CHI069,2014-07-15T00:00:00,21,NaN,NaN,NaN,NaN,NaN,2014-07
13,1111 N HUMBOLDT,CHI010,2014-07-08T00:00:00,80,NaN,NaN,NaN,NaN,NaN,2014-07
14,5520 S WESTERN,CHI069,2014-07-03T00:00:00,23,NaN,NaN,NaN,NaN,NaN,2014-07
15,1111 N HUMBOLDT,CHI010,2014-07-12T00:00:00,83,NaN,NaN,NaN,NaN,NaN,2014-07
16,7739 S WESTERN,CHI064,2014-07-10T00:00:00,73,NaN,NaN,NaN,NaN,NaN,2014-07
17,1111 N HUMBOLDT,CHI010,2014-07-17T00:00:00,69,NaN,NaN,NaN,NaN,NaN,2014-07
18,5520 S WESTERN,CHI069,2014-07-27T00:00:00,21,NaN,NaN,NaN,NaN,NaN,2014-07
19,1111 N HUMBOLDT,CHI010,2014-07-02T00:00:00,75,NaN,NaN,NaN,NaN,NaN,2014-07
20,5529 S WESTERN,CHI068,2014-07-02T00:00:00,9,NaN,NaN,NaN,NaN,NaN,2014-07
21,1111 N HUMBOLDT,CHI010,2014-07-04T00:00:00,102,NaN,NaN,NaN,NaN,NaN,2014-07
22,7738 S WESTERN,CHI065,2014-07-16T00:00:00,49,NaN,NaN,NaN,NaN,NaN,2014-07
23,5529 S WESTERN,CHI068,2014-07-20T00:00:00,25,NaN,NaN,NaN,NaN,NaN,2014-07
24,5529 S WESTERN,CHI068,2014-07-10T00:00:00,19,NaN,NaN,NaN,NaN,NaN,2014-07
25,1111 N HUMBOLDT,CHI010,2014-07-27T00:00:00,92,NaN,NaN,NaN,NaN,NaN,2014-07
26,5529 S WESTERN,CHI068,2014-07-21T00:00:00,21,NaN,NaN,NaN,NaN,NaN,2014-07
27,5529 S WESTERN,CHI068,2014-07-29T00:00:00,10,NaN,NaN,NaN,NaN,NaN,2014-07
28,5520 S WESTERN,CHI069,2014-07-18T00:00:00,18,NaN,NaN,NaN,NaN,NaN,2014-07
29,7738 S WESTERN,CHI065,2014-07-15T00:00:00,42,NaN,NaN,NaN,NaN,NaN,2014-07
...,...,...,...,...,...,...,...,...,...,...
156751,7738 S WESTERN,CHI065,2018-08-24T00:00:00,23,NaN,NaN,NaN,NaN,NaN,2018-08
156752,1315 W GARFIELD BLVD,CHI121,2018-08-24T00:00:00,29,1.168445e+06,1.868118e+06,41.793645,-87.657861,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156753,5532 S KEDZIE AVE,CHI164,2018-08-24T00:00:00,4,1.155954e+06,1.867614e+06,41.792520,-87.703676,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156754,324 E ILLINOIS ST,CHI126,2018-08-24T00:00:00,10,1.178722e+06,1.903729e+06,41.891134,-87.619089,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156755,4123 N CENTRAL AVE,CHI049,2018-08-24T00:00:00,3,1.138310e+06,1.926965e+06,41.955726,-87.766938,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156756,4429 N BROADWAY,CHI096,2018-08-24T00:00:00,3,1.168597e+06,1.929689e+06,41.962597,-87.655518,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156757,7739 S WESTERN,CHI064,2018-08-24T00:00:00,19,NaN,NaN,NaN,NaN,NaN,2018-08
156758,6818 S KEDZIE,CHI018,2018-08-24T00:00:00,33,1.156183e+06,1.859145e+06,41.769276,-87.703063,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156759,140 N ASHLAND,CHI076,2018-08-24T00:00:00,11,1.165684e+06,1.901211e+06,41.884514,-87.667042,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156760,5529 S WESTERN,CHI068,2018-08-24T00:00:00,4,NaN,NaN,NaN,NaN,NaN,2018-08
156761,2900 W OGDEN,CHI021,2018-08-24T00:00:00,88,1.157136e+06,1.892362e+06,41.860408,-87.698672,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156762,1754 N PULASKI RD,CHI157,2018-08-24T00:00:00,8,1.149395e+06,1.911608e+06,41.913375,-87.726589,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156763,324 S KEDZIE AVE,CHI123,2018-08-24T00:00:00,10,1.155058e+06,1.898247e+06,41.876599,-87.706143,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156764,5454 W IRVING PARK,CHI050,2018-08-24T00:00:00,23,1.139043e+06,1.926097e+06,41.953330,-87.764267,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156765,3542 E 95TH ST,CHI141,2018-08-24T00:00:00,1,1.201629e+06,1.842674e+06,41.723045,-87.537041,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156766,4124 W FOSTER AVE,CHI003,2018-08-24T00:00:00,111,1.147853e+06,1.934275e+06,41.975605,-87.731670,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156767,2550 W 79TH,CHI067,2018-08-24T00:00:00,2,1.160503e+06,1.852230e+06,41.750213,-87.687421,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156768,6226 W IRVING PARK RD,CHI083,2018-08-24T00:00:00,32,1.133995e+06,1.925971e+06,41.953075,-87.782826,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156769,1111 N HUMBOLDT,CHI010,2018-08-24T00:00:00,58,NaN,NaN,NaN,NaN,NaN,2018-08
156770,5471 W HIGGINS,CHI102,2018-08-24T00:00:00,26,1.139072e+06,1.931898e+06,41.969247,-87.764019,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156771,5420 S RACINE AVE,CHI118,2018-08-24T00:00:00,2,1.169209e+06,1.868739e+06,41.795333,-87.655041,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156772,5885 N RIDGE AVE,CHI093,2018-08-24T00:00:00,27,1.165004e+06,1.939248e+06,41.988904,-87.668456,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156773,4053 W NORTH AVE,CHI159,2018-08-24T00:00:00,11,1.148867e+06,1.910282e+06,41.909746,-87.728563,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156774,2417 W 103RD ST,CHI165,2018-08-24T00:00:00,3,1.161996e+06,1.836227e+06,41.706268,-87.682391,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156775,4433 N WESTERN,CHI055,2018-08-24T00:00:00,2,1.159610e+06,1.929517e+06,41.962314,-87.688565,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156776,4446 N BROADWAY,CHI097,2018-08-24T00:00:00,1,1.168459e+06,1.929792e+06,41.962881,-87.656024,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156777,4620 W BELMONT AVE,CHI086,2018-08-24T00:00:00,8,1.144831e+06,1.920910e+06,41.938988,-87.743121,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156778,5520 S WESTERN,CHI069,2018-08-24T00:00:00,12,NaN,NaN,NaN,NaN,NaN,2018-08
156779,449 N COLUMBUS DR,CHI124,2018-08-24T00:00:00,5,1.178428e+06,1.903327e+06,41.890038,-87.620179,"{'needs_recoding': False, 'human_address': '{""...",2018-08
156780,7422 S JEFFERY,CHI101,2018-08-24T00:00:00,6,1.190790e+06,1.856046e+06,41.760006,-87.576313,"{'needs_recoding': False, 'human_address': '{""...",2018-08

In [16]:
#Graph violations by address and violation month
trace = go.Scattergl(
    x = df.groupby(['ADDRESS','VIOLATION_MONTH'])['VIOLATIONS'].sum(),
    y = df['VIOLATION_MONTH'].unique(),
    mode = 'markers',
    marker = dict(
        color = '#FFBAD2',
        line = dict(width = 1)
    )
)
data = [trace]

layout= go.Layout(
    title= 'Total violations by month',
    xaxis= dict(
        title= 'Violations',
        ticklen= 5,
        zeroline= False,
        gridwidth= 2,
    ),
    yaxis=dict(
        title= 'Violations by Month',
        ticklen= 5,
        gridwidth= 2,
    ),
    showlegend= False
)
fig= go.Figure(data=data, layout=layout)
py.iplot(fig)
#py.iplot(data, filename='compare_webgl')

In [ ]:
# graph all three variables Total violations, violation  month and address
trace = go.Heatmap(z=df.groupby(['ADDRESS','VIOLATION_MONTH'])['VIOLATIONS'].sum(),
                   y=df['VIOLATION_MONTH'].unique(),
                   x=df['ADDRESS'].unique())
data=[trace]

layout= go.Layout(
    title= 'Violations by month and Address',
    xaxis= dict(
        title= 'Violations by location',
        ticklen= 5,
        zeroline= True,
        gridwidth= 2,
    ),
    yaxis=dict(
        title= 'Violations by Month',
        ticklen= 5,
        gridwidth= 2,
    ),
    showlegend= True,
    margin= dict(l=80,r=80)
)
fig= go.Figure(data=data, layout=layout)
py.iplot(fig)
#py.iplot(data, filename='labelled-heatmap')